"""add total_score to interview_sessions

Revision ID: 25f6d90b8393
Revises: c4d2af8b7522
Create Date: 2026-06-12 16:31:49.891369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f6d90b8393'
down_revision: Union[str, Sequence[str], None] = 'c4d2af8b7522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('total_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'total_score')
    # ### end Alembic commands ###
