"""add analytics scores to answers

Revision ID: 4c97fb0ed94a
Revises: 25f6d90b8393
Create Date: 2026-06-15 22:20:07.383096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c97fb0ed94a'
down_revision: Union[str, Sequence[str], None] = '25f6d90b8393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('communication_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'communication_score')
    # ### end Alembic commands ###
