"""add skills projects to resume

Revision ID: 5df4cc972f0e
Revises: 9f48dca73a99
Create Date: 2026-06-16 00:20:44.357629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df4cc972f0e'
down_revision: Union[str, Sequence[str], None] = '9f48dca73a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('projects', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'projects')
    op.drop_column('resumes', 'skills')
    # ### end Alembic commands ###
