"""add resume id to session

Revision ID: cf0549d4597b
Revises: 5df4cc972f0e
Create Date: 2026-06-16 00:34:23.597840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0549d4597b'
down_revision: Union[str, Sequence[str], None] = '5df4cc972f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('resume_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'resume_id')
    # ### end Alembic commands ###
