"""add answer scoring columns

Revision ID: f85af3882320
Revises: cf0549d4597b
Create Date: 2026-06-17 01:09:39.959735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85af3882320'
down_revision: Union[str, Sequence[str], None] = 'cf0549d4597b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('technical_depth_score', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('problem_solving_score', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'confidence_score')
    op.drop_column('answers', 'problem_solving_score')
    op.drop_column('answers', 'technical_depth_score')
    # ### end Alembic commands ###
